apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-build
spec:
  workspaces:
  - name: source
  params:
  - name: NAMESPACE
    type: string
  - name: TEST_APP
    type: string
  - name: HELM_CHART_NAME
    type: string
  - name: TEST_IMAGE
    type: string
  - name: VALUES_FILE
    type: string
  steps:
  - name: package
    image: docker.io/lachlanevenson/k8s-helm:latest
    workingDir: $(workspaces.source.path)/.
    script: |
      echo "Creating Helm package..."
      helm package helm
  - name: deploy-test
    image: docker.io/lachlanevenson/k8s-helm:latest
    workingDir: $(workspaces.source.path)/.
    script: |
      echo "Deploying Helm package..."
      pwd
      ls
      helm install $(params.TEST_APP) $(params.HELM_CHART_NAME)-*.tgz --set image.name=$(params.TEST_IMAGE) --values $(params.VALUES_FILE) -n $(params.NAMESPACE) --wait