global:
  ## Override the release name
  nameOverride:

# For example "quarkus"
runtime: quarkus

image:
  name:
  tag: latest

deploy:
  replicas: 1
  resources:
   limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /q/health/live
      port: 8080
      scheme: HTTP
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /q/health/ready
      port: 8080
      scheme: HTTP
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  env:
   - name: MESSAGE
     value: test-message

  route:
    enabled: true
    targetPort: http
    tls:
      enabled: false

service:
  port: 8080